project(game_server)

add_executable(${PROJECT_NAME})
target_compile_definitions(${PROJECT_NAME} PRIVATE $<$<BOOL:WIN32>:SPDLOG_WCHAR_TO_UTF8_SUPPORT>)
target_link_libraries(${PROJECT_NAME} PRIVATE ${CMAKE_PROJECT_NAME}-common)

set_property(SOURCE main.cpp APPEND PROPERTY
    COMPILE_DEFINITIONS
        L2CPP_SUBPROJECT_NAME="${PROJECT_NAME}"
        L2CPP_VERSION="${CMAKE_PROJECT_VERSION}"
        L2CPP_VERSION_MAJOR=${CMAKE_PROJECT_VERSION_MAJOR}
        L2CPP_VERSION_MINOR=${CMAKE_PROJECT_VERSION_MINOR}
        L2CPP_VERSION_PATCH=${CMAKE_PROJECT_VERSION_PATCH}
        L2CPP_VERSION_TWEAK=${CMAKE_PROJECT_VERSION_TWEAK}
)

file(GLOB_RECURSE SOURCES "*.cpp")
file(GLOB_RECURSE HEADERS "*.hpp")
target_sources(${PROJECT_NAME} PRIVATE $<TARGET_OBJECTS:${CMAKE_PROJECT_NAME}-common> ${SOURCES} ${HEADERS})
